name: .NET Release Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'  # Specify your .NET version here

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test

      - name: Publish the project
        run: dotnet publish --configuration Release --output ./publish

      - name: Create Release
        uses: softprops/action-gh-release@v1

        with:
          files: ./publish/**/*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
